### ISSUE TITLE
issue adding more users

### ISSUE THREAD

**Issue by killmasta93** [MarkusMcNugen/docker-sftp#7]
Hi
I was wondering if someone else has had this issue before,
Currently this is my docker compose 

```
sftp:
    image: markusmcnugen/sftp
    volumes:
        - /files:/files
    ports:
        - "3544:22"
    command: user0:xxx:::files
                     user1:xxxx:1001:100
                     user2:xxxx:1002:100
```

and its working with the user0 but the other users can login but cant see the files folder any ideas why?

Thank you
